sudo: false
cache: bundler
language: ruby
bundler_args: --without local_development
rvm:
  - 2.1
  - 2.2
  - rbx-2
  - jruby
matrix:
  fast_finish: true
notifications:
  email:
    - timo.roessner@googlemail.com
gemfile:
  - gemfiles/rails_3_0.gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
